### ISSUE TITLE
Bug with backquote/backticks in password

### ISSUE THREAD

**Issue by human228** [whs/K2AUSBKeyboard#6]
Hi!
How to reproduce:
1) pick a password like this: `tt
2) type it to USB
3) result: ` tt
There is space symbol between backquote and tt
Can anyone confirm pls?

**Comment by whs** [comment]
Seems to be this line https://github.com/whs/K2AUSBKeyboard/blob/7ce8b9596c9da13c5ef8779d0ea1e4aa429cb186/app/src/main/java/th/in/whs/k2ausbkbd/hid/Keyboard.java#L44

I'm not sure what it's doing, so I'm removing it.
